// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIdgTDKso0kkOntoeR7P07TL9npLuraxE',
    appId: '1:112096085918:web:ff37c4fb2e1914a0f7b88f',
    messagingSenderId: '112096085918',
    projectId: 'listicle-36491',
    authDomain: 'listicle-36491.firebaseapp.com',
    storageBucket: 'listicle-36491.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsEQ11X-IgP1LqB60a8x8Hh67Y1xy7d0',
    appId: '1:112096085918:android:e1fe1204ec720ed3f7b88f',
    messagingSenderId: '112096085918',
    projectId: 'listicle-36491',
    storageBucket: 'listicle-36491.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8gzCO_L1o1Lq4dgkQ0YcbYfE0f_SJhQ',
    appId: '1:112096085918:ios:201ed2621136a110f7b88f',
    messagingSenderId: '112096085918',
    projectId: 'listicle-36491',
    storageBucket: 'listicle-36491.firebasestorage.app',
    iosBundleId: 'com.example.listicleV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC8gzCO_L1o1Lq4dgkQ0YcbYfE0f_SJhQ',
    appId: '1:112096085918:ios:201ed2621136a110f7b88f',
    messagingSenderId: '112096085918',
    projectId: 'listicle-36491',
    storageBucket: 'listicle-36491.firebasestorage.app',
    iosBundleId: 'com.example.listicleV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIdgTDKso0kkOntoeR7P07TL9npLuraxE',
    appId: '1:112096085918:web:c54e4acf1ef54170f7b88f',
    messagingSenderId: '112096085918',
    projectId: 'listicle-36491',
    authDomain: 'listicle-36491.firebaseapp.com',
    storageBucket: 'listicle-36491.firebasestorage.app',
  );
}
